# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-19 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='接口名称')),
                ('request_method', models.IntegerField(choices=[(1, 'GET'), (2, 'POST')], default=1, verbose_name='请求方法')),
                ('path', models.CharField(max_length=240, unique=True, verbose_name='路径')),
                ('headers', models.TextField(blank=True, max_length=1600, null=True, verbose_name='请求头')),
                ('params', models.TextField(blank=True, max_length=1600, null=True, verbose_name='请求参数')),
                ('status', models.IntegerField(choices=[(1, '未完成'), (2, '已完成')], default=1, null=True, verbose_name='编辑状态')),
                ('create_user', models.CharField(max_length=200, verbose_name='创建用户')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('duration', models.CharField(blank=True, default='0', max_length=50, null=True, verbose_name='执行耗时')),
                ('is_active', models.IntegerField(choices=[(1, '启用'), (2, '禁用')], default=1, verbose_name='启用状态')),
                ('remark', models.TextField(blank=True, max_length=2048, null=True, verbose_name='备注信息')),
                ('response', models.TextField(blank=True, null=True, verbose_name='响应信息')),
                ('mock_path', models.CharField(blank=True, max_length=240, null=True, verbose_name='Mock地址')),
            ],
        ),
        migrations.CreateModel(
            name='MockGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='属组名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('desc', models.TextField(blank=True, max_length=1600, null=True, verbose_name='描述')),
            ],
        ),
        migrations.AddField(
            model_name='mock',
            name='group',
            field=models.ForeignKey(error_messages={'required': '请选择一个属组'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='mocks.MockGroup', verbose_name='属组'),
        ),
    ]
