# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-28 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mock',
            name='response',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='\u54cd\u5e94\u4fe1\u606f'),
        ),
    ]
