# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-29 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0003_mock_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockgroup',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='mockgroup',
            name='port',
        ),
        migrations.RemoveField(
            model_name='mockgroup',
            name='protocol',
        ),
        migrations.AlterField(
            model_name='mock',
            name='headers',
            field=models.TextField(blank=True, max_length=1600, null=True, verbose_name='\u8bf7\u6c42\u5934'),
        ),
        migrations.AlterField(
            model_name='mock',
            name='params',
            field=models.TextField(blank=True, max_length=1600, null=True, verbose_name='\u8bf7\u6c42\u53c2\u6570'),
        ),
    ]
