# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-18 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0006_auto_20180330_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockgroup',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mockgroup',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
