# Generated by Django 2.0.5 on 2018-05-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0007_auto_20180418_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mock',
            options={},
        ),
    ]
