# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(error_messages={'required': '接口名称不能为空'}, max_length=150, verbose_name='接口名称')),
                ('path', models.CharField(blank=True, max_length=600, null=True, verbose_name='路径')),
                ('protocol', models.IntegerField(choices=[(0, None), (1, 'http'), (2, 'https')], default=0, verbose_name='协议')),
                ('ip', models.CharField(blank=True, max_length=150, null=True, verbose_name='域名')),
                ('port', models.SmallIntegerField(blank=True, null=True, verbose_name='端口')),
                ('request_method', models.IntegerField(choices=[(1, 'GET'), (2, 'POST')], default=1, verbose_name='请求方法')),
                ('headers', models.CharField(blank=True, max_length=1600, null=True, verbose_name='请求头')),
                ('params', models.CharField(blank=True, max_length=1600, null=True, verbose_name='请求参数')),
                ('is_active', models.IntegerField(choices=[(1, '启用'), (2, '禁用')], default=1, verbose_name='启用状态')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('expect_res', models.TextField(blank=True, max_length=2048, null=True, verbose_name='预期结果')),
                ('response_code', models.TextField(blank=True, max_length=50, null=True, verbose_name='响应码')),
                ('response_header', models.TextField(blank=True, max_length=1600, null=True, verbose_name='响应头')),
                ('fact_res', models.TextField(blank=True, max_length=2048, null=True, verbose_name='结果响应')),
                ('duration', models.CharField(blank=True, default='0', max_length=50, null=True, verbose_name='执行耗时')),
                ('status', models.IntegerField(choices=[(1, '未执行'), (2, '成功'), (3, '失败'), (4, '错误')], default=1, verbose_name='用例状态')),
                ('request_type', models.IntegerField(choices=[(1, 'application/json'), (2, 'text/plain'), (3, 'application/xml'), (4, 'application/rdf+xml'), (5, 'text/html'), (6, 'application/x-www-form-urlencoded')], default=1, verbose_name='请求类型')),
                ('remark', models.TextField(blank=True, max_length=2048, null=True, verbose_name='备注信息')),
                ('proxies', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='代理')),
                ('NO', models.IntegerField(default=0, verbose_name='序号')),
                ('traceback', models.TextField(blank=True, max_length=2048, null=True, verbose_name='异常信息')),
            ],
            options={
                'ordering': ['NO'],
            },
        ),
        migrations.CreateModel(
            name='CaseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='案例集')),
                ('desc', models.CharField(blank=True, max_length=150, null=True, verbose_name='描述')),
                ('proxies', models.CharField(blank=True, max_length=250, verbose_name='代理')),
                ('protocol', models.IntegerField(choices=[(0, None), (1, 'http'), (2, 'https')], default=1, null=True, verbose_name='协议')),
                ('ip', models.CharField(blank=True, max_length=150, null=True, verbose_name='域名')),
                ('port', models.CharField(blank=True, max_length=150, null=True, verbose_name='端口')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('rerun', models.PositiveSmallIntegerField(default=1, verbose_name='重跑次数')),
            ],
        ),
        migrations.CreateModel(
            name='GroupResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_count', models.IntegerField(default=0, verbose_name='接口数')),
                ('res_success', models.IntegerField(default=0, verbose_name='成功')),
                ('res_fail', models.IntegerField(default=0, verbose_name='失败')),
                ('res_error', models.IntegerField(default=0, verbose_name='错误')),
                ('res_rerun', models.IntegerField(default=1, verbose_name='重跑次数')),
                ('res_duration', models.CharField(blank=True, default='0', max_length=50, null=True, verbose_name='执行耗时')),
                ('res_update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('res_add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('res_status', models.IntegerField(choices=[(1, '未执行'), (2, '成功'), (3, '失败'), (4, '错误')], default=1, verbose_name='用例状态')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='case.CaseGroup')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='case_group',
            field=models.ForeignKey(error_messages={'required': '请选择一个属组'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CaseGroup', verbose_name='用例属组'),
        ),
    ]
