# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(error_messages={'required': '\u63a5\u53e3\u540d\u79f0\u4e0d\u80fd\u4e3a\u7a7a'}, max_length=50, verbose_name='\u63a5\u53e3\u540d\u79f0')),
                ('url', models.URLField(error_messages={'required': '\u8bf7\u6c42\u5730\u5740\u4e0d\u80fd\u4e3a\u7a7a'}, max_length=100, verbose_name='URL')),
                ('request_method', models.IntegerField(choices=[(1, 'GET'), (2, 'POST')], default=1, verbose_name='\u8bf7\u6c42\u65b9\u6cd5')),
                ('headers', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8bf7\u6c42\u5934')),
                ('params', models.CharField(blank=True, max_length=150, null=True, verbose_name='\u8bf7\u6c42\u53c2\u6570')),
                ('is_active', models.IntegerField(choices=[(1, '\u542f\u7528'), (2, '\u7981\u7528')], default=1, verbose_name='\u542f\u7528\u72b6\u6001')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('expect_res', models.TextField(blank=True, max_length=150, null=True, verbose_name='\u9884\u671f\u7ed3\u679c')),
                ('fact_res', models.TextField(blank=True, max_length=150, null=True, verbose_name='\u7ed3\u679c\u54cd\u5e94')),
                ('duration', models.IntegerField(default=0, verbose_name='\u6267\u884c\u8017\u65f6')),
                ('status', models.IntegerField(choices=[(1, '\u672a\u6267\u884c'), (2, '\u6210\u529f'), (3, '\u5931\u8d25'), (4, '\u9519\u8bef')], default=1, verbose_name='\u7528\u4f8b\u72b6\u6001')),
                ('remark', models.TextField(blank=True, max_length=150, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
        ),
        migrations.CreateModel(
            name='CaseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u7ec4\u540d')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u63cf\u8ff0')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='case_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.CaseGroup', verbose_name='\u7528\u4f8b\u5c5e\u7ec4'),
        ),
    ]
