# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6267\u884c\u8017\u65f6'),
        ),
        migrations.AlterField(
            model_name='case',
            name='headers',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='\u8bf7\u6c42\u5934'),
        ),
    ]
