# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20171013_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_name',
            field=models.CharField(error_messages={'required': '\u63a5\u53e3\u540d\u79f0\u4e0d\u80fd\u4e3a\u7a7a'}, max_length=150, verbose_name='\u63a5\u53e3\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='case',
            name='duration',
            field=models.CharField(blank=True, default='0', max_length=50, null=True, verbose_name='\u6267\u884c\u8017\u65f6'),
        ),
        migrations.AlterField(
            model_name='case',
            name='expect_res',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='\u9884\u671f\u7ed3\u679c'),
        ),
        migrations.AlterField(
            model_name='case',
            name='fact_res',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='\u7ed3\u679c\u54cd\u5e94'),
        ),
        migrations.AlterField(
            model_name='case',
            name='headers',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='\u8bf7\u6c42\u5934'),
        ),
        migrations.AlterField(
            model_name='case',
            name='params',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='\u8bf7\u6c42\u53c2\u6570'),
        ),
        migrations.AlterField(
            model_name='case',
            name='remark',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='case',
            name='url',
            field=models.URLField(error_messages={'required': '\u8bf7\u6c42\u5730\u5740\u4e0d\u80fd\u4e3a\u7a7a'}, max_length=600, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='casegroup',
            name='desc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='\u63cf\u8ff0'),
        ),
    ]
