# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_auto_20171018_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='request_type',
            field=models.IntegerField(choices=[(1, 'application/json'), (2, 'text/plain'), (3, 'application/xml'), (4, 'application/rdf+xml'), (5, 'text/html'), (6, 'application/x-www-form-urlencoded')], default=1, verbose_name='\u8bf7\u6c42\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_group',
            field=models.ForeignKey(error_messages={'required': '\u8bf7\u9009\u62e9\u4e00\u4e2a\u5c5e\u7ec4'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.CaseGroup', verbose_name='\u7528\u4f8b\u5c5e\u7ec4'),
        ),
    ]
