# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_auto_20171024_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='expect_res',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='\u9884\u671f\u7ed3\u679c'),
        ),
        migrations.AlterField(
            model_name='case',
            name='fact_res',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='\u7ed3\u679c\u54cd\u5e94'),
        ),
        migrations.AlterField(
            model_name='case',
            name='headers',
            field=models.CharField(blank=True, max_length=1600, null=True, verbose_name='\u8bf7\u6c42\u5934'),
        ),
        migrations.AlterField(
            model_name='case',
            name='params',
            field=models.CharField(blank=True, max_length=1600, null=True, verbose_name='\u8bf7\u6c42\u53c2\u6570'),
        ),
        migrations.AlterField(
            model_name='case',
            name='remark',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='case',
            name='response_header',
            field=models.TextField(blank=True, max_length=1600, null=True, verbose_name='\u54cd\u5e94\u5934'),
        ),
    ]
