# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_user', models.EmailField(max_length=255, verbose_name='邮箱账号')),
                ('email_pwd', models.CharField(max_length=200, verbose_name='邮箱密码')),
                ('email_host', models.CharField(max_length=200, verbose_name='邮箱域名')),
                ('email_port', models.IntegerField(default=25, verbose_name='邮箱端口')),
                ('email_ssl', models.BooleanField(verbose_name='邮箱SSL')),
            ],
        ),
    ]
