# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('djcelery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enbale', models.BooleanField(verbose_name='邮件禁用')),
                ('email_subiect', models.CharField(max_length=200, verbose_name='邮件主题')),
                ('email_message', models.TextField(verbose_name='邮件信息')),
                ('email_to', models.CharField(max_length=200, verbose_name='收件人')),
                ('email_cc', models.CharField(max_length=400, verbose_name='抄送')),
                ('email_bcc', models.CharField(max_length=400, verbose_name='密送')),
                ('eamil_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.EmailConfig')),
                ('email_periodictask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='periodictask_email', to='djcelery.PeriodicTask')),
            ],
        ),
    ]
