# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-19 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('djcelery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enbale', models.BooleanField(verbose_name='邮件禁用')),
                ('email_subiect', models.CharField(max_length=200, verbose_name='邮件主题')),
                ('email_message', models.TextField(verbose_name='邮件信息')),
                ('email_to', models.CharField(max_length=200, verbose_name='收件人')),
                ('email_cc', models.CharField(blank=True, max_length=400, verbose_name='抄送')),
                ('email_bcc', models.CharField(blank=True, max_length=400, verbose_name='密送')),
                ('eamil_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.EmailConfig', verbose_name='发件人')),
                ('email_periodictask', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodictask_email', to='djcelery.PeriodicTask', verbose_name='定时任务')),
            ],
        ),
    ]
