# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20180428_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmanager',
            name='eamil_config',
        ),
    ]
