# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('job', '0004_remove_emailmanager_eamil_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmanager',
            name='eamil_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.EmailConfig'),
            preserve_default=False,
        ),
    ]
