# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_emailmanager_eamil_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmanager',
            name='eamil_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.EmailConfig', verbose_name='发件人'),
        ),
        migrations.AlterField(
            model_name='emailmanager',
            name='email_periodictask',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='periodictask_email', to='djcelery.PeriodicTask', verbose_name='定时任务'),
        ),
    ]
