# Generated by Django 2.0.5 on 2018-05-03 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20180503_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmanager',
            name='email_periodictask',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='periodictask_email', to='djcelery.PeriodicTask', verbose_name='定时任务'),
        ),
    ]
